project_id = "kzbmthhtbeddcjrucuex"

[functions.send-contact-email]
verify_jwt = false

[functions.chat-support]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.translate-blog-posts]
verify_jwt = false