project_id = "kzbmthhtbeddcjrucuex"

[functions.send-contact-email]
verify_jwt = false

[functions.chat-support]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.translate-blog-posts]
verify_jwt = false

[functions.generate-blog-article]
verify_jwt = false

[functions.extract-url-content]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.create-credit-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.spend-credits]
verify_jwt = false

[functions.register-work-ibs]
verify_jwt = false

[functions.ibs-webhook]
verify_jwt = false

[functions.ibs-signatures]
verify_jwt = false

[functions.ibs-webhook-signature-ok]
verify_jwt = false

[functions.ibs-webhook-signature-ko]
verify_jwt = false